# Generated by Django 4.2.13 on 2024-07-02 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Book',
                'db_table_comment': 'Question answers',
            },
        ),
    ]
