# Generated by Django 4.2.13 on 2024-07-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_book_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
    ]
