# Generated by Django 4.2.13 on 2024-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_book_title'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='book',
            table_comment=None,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
